# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  test:
    docker:
      - image: circleci/golang:1.8
    working_directory: /go/src/github.com/disaster37/check-rancher
    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run: go test -v ./...
  build:
    docker:
      - image: circleci/golang:1.8
    working_directory: /go/src/github.com/disaster37/check-rancher
    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run: go build
  release:
    docker:
      - image: circleci/golang:1.8
    working_directory: /go/src/github.com/disaster37/check-rancher
    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run: go get github.com/mitchellh/gox
      - run: go get github.com/tcnksm/ghr
      - run: sed -i 's/app.Version := "develop"/app.Version := "$BUILD_VERSION"/' check-rancher.go
      - run: gox -output "dist/ncd_{{.OS}}_{{.Arch}}"
      - run: ghr -t $GITHUB_TOKEN -u $CIRCLE_PROJECT_USERNAME -r $CIRCLE_PROJECT_REPONAME --replace `git describe --tags` dist/
workflows:
  version: 2
  build-workflow:
    jobs:
      - test
      - build
          requires:
            - test
      - release:
          requires:
            - test
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/