# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2.1
orbs:
  codecov: codecov/codecov@1.0.5

jobs:
  test:
    docker:
      - image: circleci/golang:1.13
        environment:
          GO111MODULE: "on"
    working_directory: /go/check-rancher
    steps:
      - checkout
      - run: go test -v ./...
  build:
    docker:
      - image: circleci/golang:1.13
        environment:
          GO111MODULE: "on"
    working_directory: /go/check-rancher
    steps:
      - checkout
      - run: go build
  release:
    docker:
      - image: circleci/golang:1.13
        environment:
          GITHUB_TOKEN: $GITHUB_TOKEN
          CIRCLE_PROJECT_USERNAME: $CIRCLE_PROJECT_USERNAME
          CIRCLE_PROJECT_REPONAME: $CIRCLE_PROJECT_REPONAME
          CIRCLE_TAG: $CIRCLE_TAG
          GO111MODULE: "on"
    working_directory: /go/check-rancher
    steps:
      - checkout
      - run: go get github.com/mitchellh/gox
      - run: go get github.com/tcnksm/ghr
      - run: sed -i 's/app.Version := "develop"/app.Version := "$CIRCLE_TAG"/' main.go
      - run: gox -os="freebsd darwin linux windows" -arch "386 amd64" -parallel=1  -output "dist/check_rancher_${CIRCLE_TAG}_{{.OS}}_{{.Arch}}"
      - run: CGO_ENABLED=0 gox -os="freebsd darwin linux windows" -arch "386 amd64" -parallel=1 -output "dist/check_rancher_${CIRCLE_TAG}_{{.OS}}_{{.Arch}}_static"
      - run: ghr -t $GITHUB_TOKEN -u $CIRCLE_PROJECT_USERNAME -r $CIRCLE_PROJECT_REPONAME $CIRCLE_TAG dist/
workflows:
  version: 2
  build-workflow:
    jobs:
      - test:
          filters:
            tags:
              only: /.*/
      - build:
          requires:
            - test
          filters:
            tags:
              only: /.*/
      - release:
          context: Github
          requires:
            - build
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/